---
date: `r Sys.Date()`
output: 
  word_document: 
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r functions}
library(tidyverse)

get_seatinfo <- function(filepath) {
  read_csv(filepath,
           col_types = cols(Seat = col_character(), Version = col_factor(levels = c("A", "B")),
                            Row = col_integer(), Column = col_integer()))
}

get_students <- function(filepath) { read_csv(filepath, col_names = TRUE, cols_only(Student = col_character())) %>%
  filter(Student != "Points Possible") %>%
  filter(Student != "Student, Test") %>% arrange(Student)
}


roomlayout <- function(df) {
  ggplot(df, aes(factor(Column),
                 factor(Row), 
                 label = Seat, 
                 fill = Version)) +
    geom_tile(alpha = .5) + 
    geom_text() +  
    theme_classic(14) + 
    xlab("Front") + ylab("") +
    scale_fill_manual(values = c("white", "grey30"))
}

assign_seats <- function(sdf, seats, rows) {
  num_students <- nrow(sdf)
  num_seats <- nrow(seats)
  if (num_students < num_seats) {
    sdf[(num_students + 1):num_seats, 1] <- "Unassigned"
  }

  if (rows) {
    index <- 1:num_seats
    index[1:num_students] <- sample(num_students)
    tibble(Student = sdf$Student,
         Row = seats$Seat[index],
         Version = seats$Version[index])
  } else {
    index <- sample(num_seats)
    tibble(Student = sdf$Student,
         Seat = seats$Seat[index],
         Version = seats$Version[index])
  }
  }

```

```{r, eval=FALSE, echo=FALSE}
# converting layouts from cs3157/seatingcharts
roominfo <- read_tsv("sch501.txt", col_names = FALSE) %>% 
  rownames_to_column("Row") %>% 
  gather(key = "Column", value = "Seat", -Row) %>% 
  mutate(Column = parse_number(Column),
         Row = parse_number(Row)) %>%
  mutate(Row = max(Row) + 1 - Row) %>% 
  filter(complete.cases(.)) %>% 
  mutate(Version = ifelse(Column %% 2 == 0, "A", "B")) %>% 
  select(Seat, Row, Column, Version)
  
write_csv(roominfo, "Scher501.csv")

# creating a temp version with fewer Version As
roominfo <- roominfo %>% 
  filter(!(Column == 20 & Row < 10))
write_csv(roominfo, "Scher501temp.csv")
```


```{r}
# Start here
# 1. Download grades csv from CourseWorks and put in Documents/Students folder
# 2. Set class name to csv file
# 2. Set room name

class <- "stat1201test1.csv"

room <- "HamiltonLarge.csv"

set.seed(1116)

seats <- get_seatinfo(room)

rows <- TRUE
# if (sum(seats$Seat == seats$Row) == nrow(seats)) rows <- TRUE

not_here <- c("Maitland, Anna", "Frascati, Grace", "Craigie, Luca", "Yu, Melissa", "Andersson, Sandra", "Rana, Ananya", "Fu, Victoria")

students <- get_students(paste0("~/Documents/Students/", class)) |> 
  filter(!(Student %in% not_here)) |> 
  assign_seats(seats, rows)
```

### Seating Chart
```{r}
if (rows) {
  students[,c("Student", "Row")]
  } else {
  students %>% 
      filter(Student != "Unassigned") %>% 
      select(Student, Seat) %>% 
      knitr::kable()
    }
```



```{r, eval=FALSE}
### Sorted by Seat
if (rows) {
  students %>% arrange(Row, Student) %>% 
  select("Row", "Student")
} else {
    students <- students %>%
    mutate(Seat = factor(Seat, levels = seats$Seat))
  students %>% arrange(Seat, Student) %>% select("Seat", "Version", "Student")
}
```

### Sorted by Seat
```{r}
# trying a new method that will work with Scher501
if (rows) {
  students %>% arrange(Row, Student) %>% 
  select("Row", "Student")
} else {
    students %>% 
    left_join(seats) %>% 
    arrange(Row, Column) %>% 
    mutate(Student = ifelse(Student =="Unassigned", "*Unassigned*", Student)) %>% 
    select(Seat, Version, Student) %>% 
    knitr::kable()
}
```


### Room Layout
```{r, fig.width = 10}
roomlayout(seats)
```


### Version Count
```{r}
summary(students$Version[students$Student != "Unassigned"])
```


